[options]
admin_passwd = $pbkdf2-sha512$600000$9P6/txbifC8FIETI2ft/7w$0TfvnGqvdurCVtI7ccfCAoH9jbrxcStV1FZoYQ3SSWpdv95q2gxIsjVOdG/5mo.ta5kI6grN25gubA/TKgYKTw
db_host = localhost
db_port = 5432
db_user = odoo_app
db_password = odoo_user1o0p
addons_path = D:\Python\odoo\addons,D:\Python\odoo\customaddons
http_port = 8069
proxy_mode = False
log_level = info
data_dir = D:\Python\odoodata
workers = 0
max_cron_threads = 2
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_time_cpu = 60
limit_time_real = 120
list_db = True
smtp_server = localhost
smtp_port = 25
smtp_user = False
smtp_password = False
smtp_ssl = False
email_from = False
dev_mode = reload,qweb,werkzeug,xml
test_enable = False
dbfilter = .*
longpolling_port = 8072
unaccent = False
